[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]<8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "flask_compress/_version.py"
write_to_template = "__version__ = \"{version}\"\n"
